"""add note timestamp

Revision ID: d86619569bd8
Revises: 
Create Date: 2023-04-26 23:21:01.866125

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd86619569bd8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_article', schema=None) as batch_op:
        batch_op.alter_column('editor_type',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_comment='0:富文本编辑器 1:markdown编辑器',
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_comment='-1已删除 0:待审核  1:已审核 ',
               existing_nullable=True)
        batch_op.drop_index('idx_board_id')
        batch_op.drop_index('idx_pboard_id')
        batch_op.drop_index('idx_post_time')
        batch_op.drop_index('idx_title')
        batch_op.drop_index('idx_top_type')
        batch_op.drop_index('idx_user_id')
        batch_op.create_index(batch_op.f('ix_forum_article_board_id'), ['board_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_article_p_board_id'), ['p_board_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_article_post_time'), ['post_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_article_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_article_top_type'), ['top_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_article_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('forum_article_attachment', schema=None) as batch_op:
        batch_op.alter_column('file_type',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_comment='文件类型',
               existing_nullable=True)
        batch_op.drop_index('idx_article_id')
        batch_op.drop_index('idx_user_id')
        batch_op.create_index(batch_op.f('ix_forum_article_attachment_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_article_attachment_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('forum_comment', schema=None) as batch_op:
        batch_op.drop_index('idx_article_id')
        batch_op.drop_index('idx_p_id')
        batch_op.drop_index('idx_post_time')
        batch_op.drop_index('idx_status')
        batch_op.drop_index('idx_top')
        batch_op.drop_index('idx_user_id')
        batch_op.create_index(batch_op.f('ix_forum_comment_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_comment_p_comment_id'), ['p_comment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_comment_post_time'), ['post_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_comment_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_comment_top_type'), ['top_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_comment_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('like_record', schema=None) as batch_op:
        batch_op.alter_column('op_type',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_comment='操作类型0:文章点赞 1:评论点赞',
               existing_nullable=True)

    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.alter_column('sex',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_comment='0:女 1:男',
               existing_nullable=True)

    with op.batch_alter_table('user_integral_record', schema=None) as batch_op:
        batch_op.alter_column('oper_type',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_comment='操作类型',
               existing_nullable=True)

    with op.batch_alter_table('user_message', schema=None) as batch_op:
        batch_op.alter_column('message_type',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_comment='0:系统消息 1:评论 2:文章点赞  3:评论点赞 4:附件下载',
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_comment='1:未读 2:已读',
               existing_nullable=True)
        batch_op.drop_index('idx_received_user_id')
        batch_op.drop_index('idx_status')
        batch_op.drop_index('idx_type')
        batch_op.create_index(batch_op.f('ix_user_message_message_type'), ['message_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_message_received_user_id'), ['received_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_message_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_message_status'))
        batch_op.drop_index(batch_op.f('ix_user_message_received_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_message_message_type'))
        batch_op.create_index('idx_type', ['message_type'], unique=False)
        batch_op.create_index('idx_status', ['status'], unique=False)
        batch_op.create_index('idx_received_user_id', ['received_user_id'], unique=False)
        batch_op.alter_column('status',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_comment='1:未读 2:已读',
               existing_nullable=True)
        batch_op.alter_column('message_type',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_comment='0:系统消息 1:评论 2:文章点赞  3:评论点赞 4:附件下载',
               existing_nullable=True)

    with op.batch_alter_table('user_integral_record', schema=None) as batch_op:
        batch_op.alter_column('oper_type',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_comment='操作类型',
               existing_nullable=True)

    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.alter_column('sex',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_comment='0:女 1:男',
               existing_nullable=True)

    with op.batch_alter_table('like_record', schema=None) as batch_op:
        batch_op.alter_column('op_type',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_comment='操作类型0:文章点赞 1:评论点赞',
               existing_nullable=True)

    with op.batch_alter_table('forum_comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forum_comment_user_id'))
        batch_op.drop_index(batch_op.f('ix_forum_comment_top_type'))
        batch_op.drop_index(batch_op.f('ix_forum_comment_status'))
        batch_op.drop_index(batch_op.f('ix_forum_comment_post_time'))
        batch_op.drop_index(batch_op.f('ix_forum_comment_p_comment_id'))
        batch_op.drop_index(batch_op.f('ix_forum_comment_article_id'))
        batch_op.create_index('idx_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_top', ['top_type'], unique=False)
        batch_op.create_index('idx_status', ['status'], unique=False)
        batch_op.create_index('idx_post_time', ['post_time'], unique=False)
        batch_op.create_index('idx_p_id', ['p_comment_id'], unique=False)
        batch_op.create_index('idx_article_id', ['article_id'], unique=False)

    with op.batch_alter_table('forum_article_attachment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forum_article_attachment_user_id'))
        batch_op.drop_index(batch_op.f('ix_forum_article_attachment_article_id'))
        batch_op.create_index('idx_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_article_id', ['article_id'], unique=False)
        batch_op.alter_column('file_type',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_comment='文件类型',
               existing_nullable=True)

    with op.batch_alter_table('forum_article', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forum_article_user_id'))
        batch_op.drop_index(batch_op.f('ix_forum_article_top_type'))
        batch_op.drop_index(batch_op.f('ix_forum_article_title'))
        batch_op.drop_index(batch_op.f('ix_forum_article_post_time'))
        batch_op.drop_index(batch_op.f('ix_forum_article_p_board_id'))
        batch_op.drop_index(batch_op.f('ix_forum_article_board_id'))
        batch_op.create_index('idx_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_top_type', ['top_type'], unique=False)
        batch_op.create_index('idx_title', ['title'], unique=False)
        batch_op.create_index('idx_post_time', ['post_time'], unique=False)
        batch_op.create_index('idx_pboard_id', ['p_board_id'], unique=False)
        batch_op.create_index('idx_board_id', ['board_id'], unique=False)
        batch_op.alter_column('status',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_comment='-1已删除 0:待审核  1:已审核 ',
               existing_nullable=True)
        batch_op.alter_column('editor_type',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_comment='0:富文本编辑器 1:markdown编辑器',
               existing_nullable=False)

    # ### end Alembic commands ###
